name: tm_ressource_tracker
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.0.2+14

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  shared_preferences: ^2.2.2
  get_it: ^7.6.4
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  auto_size_text: ^3.0.0
  sliver_tools: ^0.2.12
  flutter_i18n: ^0.33.0
  logger: ^2.0.2+1
  json_locale_generator: ^0.2.4
  collection: ^1.17.1
  appwrite: ^8.1.0
  uuid: ^4.1.0
  device_info: ^2.0.3
  pull_to_refresh: ^2.0.0
  vibration: ^1.7.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  freezed: ^2.4.5
  r_flutter: ^0.9.0
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  fonts:
    - family: Enter Sansman
      fonts:
        - asset: assets/fonts/entsani.ttf
          style: italic
        - asset: assets/fonts/entsans.ttf
  assets:
    - assets/images/
    - assets/locales/
  uses-material-design: true

json_to_dart:
  sample_files:
    - source: assets/locales/en.json
      class_name: LocaleKeys
      plural_matcher: -[0-9]*$