name: appwrite_function
description: Cloud function triggered when a team membership is deleted. 
  If the member was the team owner, deletes the team and removes all data linked to the team
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  dart_appwrite: ^7.1.0
      
dev_dependencies:
  lints: ^2.0.1
